version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      k8s.io:
        patterns:
          - "k8s.io/*"
      github.com/onsi:
        patterns:
          - "github.com/onsi/ginkgo/*"
          - "github.com/onsi/gomega/*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
