apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: JiraCluster
metadata:
  labels:
    app.kubernetes.io/name: jiracluster
    app.kubernetes.io/instance: jiracluster-sample
    app.kubernetes.io/part-of: cluster-api-provider-jira
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cluster-api-provider-jira
  name: jiracluster-sample
spec:
  # TODO(user): Add fields here
